#ifndef _ASSEMBLY_H_
#define _ASSEMBLY_H_

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "instruction.h"

struct LABEL_ENTRY_T{
	char* name;
	unsigned int offset;
};

#define ASSEMBLY_FLAG_NULL 0
#define ASSEMBLY_FLAG_ZERO_PAGE 0x1
#define ASSEMBLY_FLAG_ABSOLUTE 0x2
#define ASSEMBLY_FLAG_IMMEDIATE 0x4
#define ASSEMBLY_FLAG_X 0x8
#define ASSEMBLY_FLAG_Y 0x10
#define ASSEMBLY_FLAG_INDIRECT_INDEXED 0x20
#define ASSEMBLY_FLAG_INDEXED_INDIRECT 0x40
#define ASSEMBLY_FLAG_INDIRECT 0x80

#define ASSEMBLY_OP_FLAG_NULL 0
#define ASSEMBLY_OP_FLAG_LABEL 1
#define ASSEMBLY_OP_FLAG_NUMBER 2

#define ASSEMBLY_TYPE_NULL 0
#define ASSEMBLY_TYPE_ORA 1
#define ASSEMBLY_TYPE_AND 2
#define ASSEMBLY_TYPE_EOR 3
#define ASSEMBLY_TYPE_ADC 4
#define ASSEMBLY_TYPE_STA 5
#define ASSEMBLY_TYPE_LDA 6
#define ASSEMBLY_TYPE_CMP 7
#define ASSEMBLY_TYPE_SBC 8
#define ASSEMBLY_TYPE_ASL 9
#define ASSEMBLY_TYPE_ROL 10
#define ASSEMBLY_TYPE_LSR 11
#define ASSEMBLY_TYPE_ROR 12
#define ASSEMBLY_TYPE_STX 13
#define ASSEMBLY_TYPE_LDX 14
#define ASSEMBLY_TYPE_DEC 15
#define ASSEMBLY_TYPE_INC 16
#define ASSEMBLY_TYPE_BIT 17
#define ASSEMBLY_TYPE_JMP 18
#define ASSEMBLY_TYPE_STY 19
#define ASSEMBLY_TYPE_LDY 20
#define ASSEMBLY_TYPE_CPY 21
#define ASSEMBLY_TYPE_CPX 22
#define ASSEMBLY_TYPE_BPL 23
#define ASSEMBLY_TYPE_BMI 24
#define ASSEMBLY_TYPE_BVC 25
#define ASSEMBLY_TYPE_BVS 26
#define ASSEMBLY_TYPE_BCC 27
#define ASSEMBLY_TYPE_BCS 28
#define ASSEMBLY_TYPE_BNE 29
#define ASSEMBLY_TYPE_BEQ 30
#define ASSEMBLY_TYPE_BRK 31
#define ASSEMBLY_TYPE_JSR 32
#define ASSEMBLY_TYPE_RTI 33
#define ASSEMBLY_TYPE_RTS 34
#define ASSEMBLY_TYPE_PHP 35
#define ASSEMBLY_TYPE_PLP 36
#define ASSEMBLY_TYPE_PHA 37
#define ASSEMBLY_TYPE_PLA 38
#define ASSEMBLY_TYPE_DEY 39
#define ASSEMBLY_TYPE_TAY 40
#define ASSEMBLY_TYPE_INY 41
#define ASSEMBLY_TYPE_INX 42
#define ASSEMBLY_TYPE_CLC 43
#define ASSEMBLY_TYPE_SEC 44
#define ASSEMBLY_TYPE_CLI 45
#define ASSEMBLY_TYPE_SEI 46
#define ASSEMBLY_TYPE_TYA 47
#define ASSEMBLY_TYPE_CLV 48
#define ASSEMBLY_TYPE_CLD 49
#define ASSEMBLY_TYPE_SED 50
#define ASSEMBLY_TYPE_TXA 51
#define ASSEMBLY_TYPE_TXS 52
#define ASSEMBLY_TYPE_TAX 53
#define ASSEMBLY_TYPE_TSX 54
#define ASSEMBLY_TYPE_DEX 55
#define ASSEMBLY_TYPE_NOP 56

struct LABEL_ENTRY_T* make_label_entry(char* name, int offset);
int delete_label_entry(struct LABEL_ENTRY_T* src);

int add_label_entry(struct LABEL_ENTRY_T* src); // adds label entry to table 

int add_to_program(unsigned short flags, char type, void* op1, void* op2);

#endif